<?php include('../includes/_config.php');
$meta_title = = ' Location Intelligence | Real-time Location Data | Consumer Insights | Omni-Channel marketing | Retailers  ';
$meta_desc = "Location Intelligence helps retailers to analyse real-time data generated by various devices to curate accurate audience profiles, increase loyalty and sales, and even link online behaviour with real-world activity. ";
$title ="Q&A with Ken Parnham: Retailers & Location Data";
?>

<!DOCTYPE html>
<html class="background-100-e">
	<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title><?php echo $meta_title; ?></title>
    <meta name="title" content="<?php echo $meta_title; ?>" />
    <meta name="description" content="<?php echo $meta_desc; ?>" />   
	<meta property="og:title" content="<?php echo $title; ?>" />
    <meta property="og:description" content="<?php echo $meta_desc; ?>" />
    <meta property="og:image" content="<?php IMAGE('news/q-and-a-with-ken-parnham-retailers-and-location-data.png'); ?>" />
    <meta name="KEYWORDS" content="" />
    <meta name="AUTHOR" content="Near" />
    <meta name="RATING" content="General" />
    <meta name="ROBOTS" content="index, follow" />
    <meta name="REVISIT-AFTER" content="30 days" />
    <?php include('../includes/_head.php'); ?>
	<link rel="stylesheet" href="<?php CSS('filter.css'); ?>" />
     <link rel="stylesheet" href="<?php  CSS('social-buttons.css'); ?>">
	</head>
	<body class="state1 background-100-e">
		<!-- BEGIN: Top menu -->
			<?php include('../includes/_header.php'); ?>
		<!-- END: Top menu -->
        <div class="overlay-window gallery-overlay colors-f background-95-f" data-overlay-zoom="#work .content">
			<div class="overlay-control background-85-d">
				<a class="previos" href="#"></a>
				<a class="next" href="#"></a>
				<a class="cross" href="#"></a>
			</div>
			<div class="overlay-view"></div>
			<ul class="loader">
				<!--li class="background-100-d"></li>
				<li class="background-100-d"></li>
				<li class="background-100-d"></li-->
			</ul>
		</div>
		<div class="overlay-window map-overlay colors-f background-95-f">
			<div class="overlay-control background-90-f">
				<a class="cross" href="#"></a>
			</div>
			<div class="overlay-view">
				<div class="map-canvas" data-latitude="42.487606" data-longitude="-71.115661" data-zoom="14">
					<div class="map-marker" data-latitude="42.487606" data-longitude="-71.115661" data-text="Our awesome location"></div>
					<div class="map-marker" data-latitude="42.485100" data-longitude="-71.113256" data-text="Our sales office"></div>
				</div>
			</div>
		</div>
		<div class="gate colors-e background-solid">
			<div class="gate-bar background-highlight-e"></div>
			<ul class="loader">
				<!--li class="background-100-g"></li>
				<li class="background-90-c"></li>
				<li class="background-100-f"></li-->
			</ul>
		</div>
		<!-- BEGIN: Page content -->
	
            
            <div class="view sub-banner">
        <div class="overlay-vdo2" ></div>
				<img alt class="bg" src="<?php  IMAGE('bg-news.png'); ?>" /><img alt class="bg" src="<?php IMAGE('bg-news.png'); ?>" />
				<div class="content one-third-size colors-e background-60" style="z-index:2">
					<div class="container">
						<h2><?php echo $title; ?></h2>
						<!--<p class="title">Policy</p>-->
					</div>
				</div>
			</div>
		<section>
			<div class="view">
				<div class="content  colors-e background-90-e">
					<div class="container">
						<div class="row">
							<div class="col-md-9">
								<div class="row post">
									<div class="col-md-3 post-meta">
									<div class="post-date">
										<div class="post-day">30</div>
										<div class="post-month">Sep 2016</div>
										</div>
										<div class="post-author"><i class="fa fa-map-marker"></i>&nbsp; London</div>
									</div>
									<div class="col-md-9">
										<div class="post-body background-75-e">
											<div class="post-image">
											<img class="fluid-width" src="<?php IMAGE('news/q-and-a-with-ken-parnham-retailers-and-location-data.png'); ?>" alt="Q&A with Ken Parnham: Retailers & Location Data">
											</div>
											<h4 style="text-align:left; margin-bottom: 20px;"><?php echo $title; ?></h4>
											
<p class="question" style="font-size:15px;">Ken Parnham, general manager Europe at Near, asks if retailers are making the most of location intelligence in the bid for increased consumer personalisation.</p>

<p>Most retail brands are familiar with the roll call for personalisation. They can list it in their sleep: consumers want relevance, value, and consistency across every channel. But delivering a shopping experience to answer it isn’t so easy.</p>

             							 <p>The traditional path to purchase is gone. Modern consumers are channel-hoppers who might research a product via desktop, compare prices on a smartphone, and finally buy in-store. Indeed, the average consumer uses five connected devices to make a single purchase.</p>
                                
                                         
                                    
                                         <p>But this challenge has created its own solution: data. Note that consumers use multiple connected devices — tech that can access the web anywhere, tech that is mobile. With greater mobile adoption has come a rise in the volume of insights from consumers on the move, opening a world of opportunities for retailers to better connect with them. </p>
                                         
                                       <p>Using location intelligence, forward-thinking retailers can analyse the real-time data generated by a range of devices to build accurate individual profiles, increase loyalty and sales, and even link online behaviour with real-world activity.</p>
                                       
                               
 <p class="question" style="font-size:15px;">So what is location intelligence and how can retailers use it effectively?</p>
 
 <p>Fundamentally, location intelligence is a mixture of business insights and geospatial data, the value of which is revealed by cartographic tools that explore and decode the links between geography, and consumer data. The spatial abilities of this technology have advanced quickly and can now connect business information with data from many areas, such as customer relationship management (CRM) and enterprise resource planning (ERP), and mine the overall pool for useful information.</p>
 
 
 <p> With such sophisticated software at hand, retailers can at last gather all of their data sources in one place and turn the disordered mass into accurate, actionable, real-time insight. Not only does this help retailers understand complex, multi-channel journeys, but it also empowers them to influence consumer decisions by putting data to immediate use, enhancing strategy and performance while keeping competitors at bay.</p>
 
 <p class="question" style="font-size:15px;"> What can it do for retailers?</p>
 <p>The greatest retail benefit of location intelligence is its capacity to identify key moments for delivering meaningful interactions, online and offline, in real-time. Whether it’s a consumer who has been researching tablet prices and is currently standing outside a rival tech store, or a shopper checking offers for specific stores online, location intelligence can pinpoint opportunities to strengthen relationships, loyalty, and sales.</p>

<p> For example, Starbucks has done just that by adding a mobile order option to its app. Instead of waiting in the queue, consumers can find nearby branches and place orders before they arrive — making their experience more convenient, enjoyable, and repeatable.</p>

<p>Yet location intelligence has more to offer than timely messaging. It can also be used to inform business decisions, such as where to place new stores, and facilitate precise attribution by linking device identifiers to location footprints and measuring every interaction, and purchase, in a consumer’s journey. Retailers can also use their understanding of consumers to action omni-channel targeting and closely track its impact across channels.  </p>
<h4 style="text-align:left; font-size:17px; margin-top: 30px;">Top 3 retail applications of location intelligence:</h4>		
<p><span class="question"> 1. Merchandising mix: </span>The appeal of a product can depend greatly on shopper demographics, time of year or even the weather, so retailers must be agile. With real-time location intelligence, they can instantly identify who is buying what, where, and when — ensuring merchandising is always aligned with current needs and trends.</p>		

<p><span class="question"> 2. Experiment with pricing and promotions: </span>By extracting the hidden value within their own data, retailers can experiment with offers, discounts, and stock rotation to determine which strategies are most successful and discontinue those that are not, without waiting for external analysis.</p>	
	
<p><span class="question">  3. Omni-channel campaigns: </span>At present, many retailers work with different data providers, making it difficult to generate a complete view of individual consumers and engage them across channels. By amalgamating insights, location intelligence enables them to understand where messages will have the greatest impact and deliver the best experience.</p>
<p> With 40% of global shoppers frequently purchasing via mobile and almost 50% keen to see tailored recommendations in store, it’s clear that consumers expect a connected shopping experience. And location intelligence offers a way to deliver it.</p>	
<p> By utilising the latest technologies to blend mobile data with business insight, retailers can follow the twists and turns of channel-hopping consumer journeys, identify the best time to reach them, and finally answer the roll call for personalised, data-driven shopping.</p>					 


<p>As published in  <a href="http://www.retailtechnology.co.uk/news/6143/location-location-location-intelligence/" target="_blank">Retail Technology </a>.</p>

<div class="post-tags styled-list">
												<i class="fa fa-tags"></i>
												<ul>
													<li><a class="page-transition" href="<?php echo SITE_URL; ?>news/tags/retail-technology.php">Retail Technology</a></li>
													
												</ul>
											</div>








<div class="container news">
             <div class="social-share">
           		<div class="social-sharing is-clean" data-permalink="<?php my_url(); ?>">

    <!-- https://developers.facebook.com/docs/plugins/share-button/ -->
    <a target="_blank" href="http://www.facebook.com/sharer.php?u=<?php my_url(); ?>" class="share-facebook">
      <span class="fb-icon icon1"><i class="fa fa-facebook" style="font-style:normal; padding-left:7px;"></i><i class="share">Share</i></span>
      <span class="share-count">0</span>
    </a>

    <!-- https://dev.twitter.com/docs/intents -->
    <a target="_blank" href="http://twitter.com/share?url=<?php my_url(); ?>&amp;text=Q and A with Ken Parnham: Retailers and Location Data&amp;via=Near&amp;count=true" class="share-twitter" > <span class="twitter-icon icon1"><i class="fa fa-twitter" style="font-style:normal; padding-left:7px;"></i><i class="share">Tweet</i></span>
      <span class="share-count">0</span>
    </a>

</div>
            
            </div>
            
           
            </div>
										</div>
									</div>
								</div>
							</div>
						<?php include('../includes/_news-filter.php'); ?>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- END: Page content -->
	
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
   <!-- BEGIN: Footer -->
		<?php include('../includes/_footer.php'); ?>
		<!-- END: Footer -->
	<?php include('../includes/_java_scripts.php'); ?>
	<script src="<?php JS('social-buttons.js'); ?>" type="text/javascript"></script>  

  </body>
</html>
