<?php include('../includes/_config.php');
$meta_title = 'Three data trends that will define 2017 | Anil Mathews | Near | Ambient Intelligence Platform';
$meta_desc = "Anil Mathews, Founder & CEO at Near discusses the data trends that will go big in 2017 and what businesses needed to watch out for - Data Converging platforms, Adoption of AI as key highlights.";
$meta_keywords ="Ambient Intelligence Platform, Data Products, Data Convergence, Mobile data, Wearables Data, IoT Data, Augmented Reality, Brand Marketers, Retailers, Retail, Retail Analytics, Location Analytics, Consumer Insights, Data Analytics, Anil Mathews,  Mobile Location, Audience Insights, Retail Data, Attribution Analytics, Data Fusion, Brand ROI";
$title ='Three Data Trends that will Define 2017';
$meta_image="blog/three-data-trends-that-will-define-2017.png";
?>
<!doctype html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><html lang="en"><![endif]-->
<html  lang="en">
<head>
	<?php include('../includes/_head.php'); ?>
	<link rel="stylesheet" href="<?php CSS_path('page/jquery.snippet.min.css'); ?>" >
</head>

   <body>
	<div class="preloader"></div>
	<?php include('../includes/_navigation.php'); ?>
		<?php include('blog-banner.php'); ?>
		<!-- BEGIN: Page content -->
		<div class="view newsroom" style="margin-top: 100px;">
				<div class="content  colors-e background-90-e blog" id="main-content">
					<div class="container">
						<div class="row"><?php include('../includes/_blog-filter.php'); ?>
							<div class="col-md-9 col-md-pull-9">
								<div class="row post">
									<div class="col-md-3 post-meta sticky1">
									<div class="post-date">
										<div class="post-day">03</div>
										<div class="post-month">Jan 2017</div></div>
										<div class="post-author"><img src="<?php IMAGE('bb.png'); ?>" width="120" height="120" style="background: url(<?php IMAGE('near-team.png'); ?>); background-position: 0 0px; background-size: 100% auto;" alt=""/></div>
										<div class="post-author"><i class="fa fa-user"></i>&nbsp;<b> By Anil Mathews</b></div>
									</div>
									<div class="col-md-9">
										<div class="post-body background-75-e">
											<div class="post-image">
												<img class="fluid-width" src="<?php IMAGE('blog/three-data-trends-that-will-define-2017.png'); ?>" alt="">
											</div>
											<h2 style="text-align:left;"><?php echo $title; ?></h2>
											<p>2017 is nigh, and it’s the time of the year to look into the crystal ball and try to predict what the future holds for us. Here are the trends we think will go big in the coming year and what businesses need to watch out for:</p>



<h2 style="font-size:18px; text-align:left; margin-bottom: 0px;">Emergence of Data Converging Platforms</h2>
<p>Wearables are ubiquitous; everyone worth their salt is jumping on the Internet of Things (IoT) bandwagon; and Augmented Reality (AR) is here to stay. These are the current favorite trends in the industry; and based on what we’ve seen in the recent years, we think it’ll be mostly how businesses apply these trends that will drive the growth of these technologies, not the end users. </p>
<p>And here is why - the data generated by these three technologies is incredibly voluminous, we all know that. It might not be of much use to an individual user, but in large volumes can be incredibly useful to businesses. If we can handle its relentless onslaught, this data can especially provide us deep real-time analytical insights that can help brands understand their consumers far better and make data-driven decisions. </p>
<p>Data-converging platforms that will converge the influx of all connected data will rise in 2017, fuelled by the demand to tame this massive data. A converged platform has a lot to offer - from richer analytical insights, leading to focused product development, in turn leading to higher Return on Investments (ROI). A consistent and unified framework for development will bring down DevOps costs and can even provide a unified administration framework to monitor and analyze the influx of data.</p>


<h2 style="text-align:left; font-size:18px; margin-bottom: 0px;">Increased Adoption of Artificial Intelligence (AI)</h2>

<p>Like it was with big data a few years back and then machine learning a little later, AI is the current buzzword that has got everyone excited. </p>

<p>And for a reason - AI marries powerful machine learning models with efficient analytical algorithms. The result is intelligent automation and Natural Language Processing (NLP) that can help us understand human behavior that just models or just analytics separately cannot. </p>


<p>According to the recent <a href="http://www.marketsandmarkets.com/Market-Reports/artificial-intelligence-market-74851580.html" target="_blank">study</a>, overall AI market is expected to be worth $16.06 Billion by 2022, growing at a CAGR of 62.9% from 2016 to 2022. </p>

<p>We believe that the reason for this tremendous interest and excitement is simple and well-deserved. AI will strengthen real-life analyses and enable us to draw deeper, more meaningful, and relevant conclusions that will help us build insights and make connections that we have so far not been able to tap into.  </p>
<p>AI will not only have a tremendous impact in the field of digital marketing, but also customer service because we see it as a powerful tool for enhancing the overall customer experience. </p>
<p>As brands adopt AI, they will explore and try to find the best ways to use it for their business, and help them solve problems in an efficient and faster manner.</p>

<h2 style="text-align:left; font-size:18px; margin-bottom: 0px;">Uncomplicating Data - Solution by Design</h2>

<p>Think of the best products and applications you have used. It certainly wouldn’t be the ones that were full of latest and greatest features; what most probably would be on your top 5 list would be the ones that were simple to use, were intuitive, and were clean! Great design is the key to great products.</p>
<p>Complexity is a strict no-no in the world of user experience. But when you are dealing with 10 TBs of distributed data in less than a day, complexity is all you can expect. However, complex need not and must not(!) be complicated. Complexity may be unavoidable if your workflows are complex, but just because your productis handling and processing an onslaught of complex data is not a valid excuse for bad design or a difficult interface.</p>
<p>In the coming years, with every other solution dealing with complex, real-time data and analytics, the differentiator will be how you simplify the data and how simple and user-friendly you present your solution to be. The key will be “data-driven” and “informed” design, thinking beyond complicated algorithms, analytics, and automation, and deeply understanding the real-world user workflows.</p>

<p>Also published in <a href="https://www.iabaustralia.com.au/big-tent-blog/entry/three-data-trends-that-will-define-2017" target="_blank">IAB Australia</a></p>

<div class="container news">
             <div class="social-share">
           		 <div class="social-sharing is-clean" data-permalink="<?php my_url(); ?>">

    <!-- https://developers.facebook.com/docs/plugins/share-button/ -->
    <a target="_blank" href="http://www.facebook.com/sharer.php?u=<?php my_url(); ?>" class="share-facebook">
      <span class="fb-icon icon1"><i class="fa fa-facebook" style="font-style:normal; padding-left:7px;"></i><i class="share">Share</i></span>
      <span class="share-count">0</span>
    </a>

    <!-- https://dev.twitter.com/docs/intents -->
    <a target="_blank" href="http://twitter.com/share?url=<?php my_url(); ?>&amp;text=<?php echo $title; ?>&amp;via=Near&amp;count=true" class="share-twitter" data-dnt="true" data-counturl="<?php my_url(); ?>"> <span class="twitter-icon icon1"><i class="fa fa-twitter" style="font-style:normal; padding-left:7px;"></i><i class="share">Tweet</i></span>
      <span class="share-count">0</span>
    </a>

</div>
            
            </div>
            <div class="fb-comments" data-href="<?php my_url(); ?>" data-width="100%" data-numposts="5"></div>
           
            </div>
										</div>
									</div>
								</div>
							</div>
				
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- END: Page content -->
   <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
   <!-- BEGIN: Footer -->
<?php include('../includes/_footer.php'); ?>
		<!-- END: Footer -->
	<?php include('../includes/_java_scripts.php'); ?>
	<script src="<?php JS('social-buttons.js'); ?>" type="text/javascript"></script>  
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4&appId=1409295566038536";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
             <script>
$(function() {
	var Accordion = function(el, multiple) {
		this.el = el || {};
		this.multiple = multiple || false;

		// Variables privadas
		var links = this.el.find('.link');
		// Evento
		links.on('click', {el: this.el, multiple: this.multiple}, this.dropdown)
	}

	Accordion.prototype.dropdown = function(e) {
		var $el = e.data.el;
			$this = $(this),
			$next = $this.next();

		$next.slideToggle();
		$this.parent().toggleClass('open');

		if (!e.data.multiple) {
			$el.find('.submenu').not($next).slideUp().parent().removeClass('open');
		};
	}	

	var accordion = new Accordion($('#accordion'), false);
});

var stickySidebar = $('.sticky');

if (stickySidebar.length > 0) { 
  var stickyHeight = stickySidebar.height(),
      sidebarTop = stickySidebar.offset().top;
}

// on scroll move the sidebar
$(window).scroll(function () {
  if (stickySidebar.length > 0) { 
    var scrollTop = $(window).scrollTop();
            
    if (sidebarTop < scrollTop) {
      stickySidebar.css('top', scrollTop - sidebarTop);

      // stop the sticky sidebar at the footer to avoid overlapping
      var sidebarBottom = stickySidebar.offset().top + stickyHeight,
          stickyStop = $('.blog').offset().top + $('.blog').height();
      if (stickyStop < sidebarBottom) {
        var stopPosition = $('.blog').height() - stickyHeight;
        stickySidebar.css('top', stopPosition);
      }
    }
    else {
      stickySidebar.css('top', '0');
    } 
  }
});

$(window).resize(function () {
  if (stickySidebar.length > 0) { 
    stickyHeight = stickySidebar.height();
  }
});



</script>
<script>
var stickySidebar1 = $('.sticky1');

if (stickySidebar1.length > 0) { 
  var stickyHeight1 = stickySidebar1.height(),
      sidebarTop1 = stickySidebar1.offset().top;
}

// on scroll move the sidebar
$(window).scroll(function () {
  if (stickySidebar1.length > 0) { 
    var scrollTop1 = $(window).scrollTop();
            
    if (sidebarTop1 < scrollTop1) {
      stickySidebar1.css('top', scrollTop1 - sidebarTop1);

      // stop the sticky sidebar at the footer to avoid overlapping
      var sidebarBottom1 = stickySidebar1.offset().top + stickyHeight1,
          stickyStop1 = $('.post').offset().top + $('.post').height();
      if (stickyStop1 < sidebarBottom1) {
        var stopPosition1 = $('.post').height() - stickyHeight1;
        stickySidebar1.css('top', stopPosition1);
      }
    }
    else {
      stickySidebar1.css('top', '0');
    } 
  }
});

$(window).resize(function () {
  if (stickySidebar1.length > 0) { 
    stickyHeight1 = stickySidebar1.height();
  }
});
</script>
     </body>
</html>