<script src='http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js'></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenMax.min.js"></script> 
<script src="http://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.5.0/lodash.min.js"></script> 
<script src="<?php JS('jquery.min.js'); ?>"></script>
<script src="<?php JS('sine-waves.min.js'); ?>"></script>
<script src="<?php JS('bootstrap.min.js'); ?>"></script>
<script src="<?php JS('slick.min.js'); ?>"></script>
<script src="<?php JS('modernizr.js'); ?>"></script>
<script src="<?php JS('typed.js'); ?>"></script>
<script src="<?php JS('particles.js'); ?>"></script>
<script src="<?php JS('aos.js'); ?>"></script>
<script src="<?php JS('masonry.pkgd.min.js'); ?>"></script>
	<script src="<?php JS('jquery.flexslider-min.js'); ?>"></script>
<script src="<?php JS('custom.js'); ?>"></script>
